# Generated by Django 2.2.7 on 2020-08-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders_ammount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=90)),
                ('email', models.CharField(default='', max_length=90)),
                ('password', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
