# Generated by Django 2.2.7 on 2020-08-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200803_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(default='', max_length=90),
        ),
    ]
